///<reference types="cypress"/>

import { SigninPage } from "../pageObject/SigninPage"
import { RecipientListPage } from "../pageObject/RecipientListPage";
import { NewPaymentPage } from "../pageObject/NewPaymentPage";
const signinpage = new SigninPage;
const recipientlist = new RecipientListPage;
const newpayment = new NewPaymentPage;

describe('Additional Currencies Test Cases', () => {
    const userName = Cypress.config('users').user1.username
    const password = Cypress.config('users').user1.password
    const userEEA = Cypress.config('users').user4.username
    const passwordEEA = Cypress.config('users').user4.password

    it('TC_AC-001-if Currency= SGD and Country = UNITED KINGDOM & client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'SGD', '')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('United Kingdom')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-002-if Currency= SGD and Country = SINGHAPORE & client = UK and check priority and regular settlement are enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('SINGAPORE', 'SGD', '')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddAccountNumber('13071472')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('SINGAPORE')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.EnabledRegularButton()
    })
    it('TC_AC-003-if Currency= SGD and Country = UNITED KINGDOM & client = EEA and check priority settlement enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'SGD', '')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-004-if Currency= SGD and Country = SINGAPORE & client = EEA and check priority and regular settlement are enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('SINGAPORE', 'SGD', '')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddAccountNumber('13071472')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('SINGAPORE')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.EnabledRegularButton()
    })
    it('TC_AC-005-if Currency= MXN and Country = UK & client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'MXN', '')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('SINGAPORE')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-006-if Currency= MXN and Country = Mexico & client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('MEXICO', 'MXN')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddCLABE('032180000118359719')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddPostCode('11115')
        recipientlist.AddState('washington')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('MEXICO')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-007-if Currency= MXN and Country = UK & client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UNITED KINGDOM', 'MXN')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })

    it('TC_AC-008-if Currency= MXN and Country = Mexico & client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('MEXICO', 'MXN')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddCLABE('032180000118359719')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddPostCode('11115')
        recipientlist.AddState('washington')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('MEXICO')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-009- Verify that the CLABE No is requested if Country = Mexico regardless of currency and Client = UK', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('MEXICO', 'MXN')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddCLABE(null)
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddPostCode('11115')
        recipientlist.AddState('washington')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('MEXICO')
        recipientlist.clickAddRecipient()
        recipientlist.validateCLABEError()
    })
    it('TC_AC-10- Verify that the CLABE No is requested if Country = Mexico regardless of currency and Client = EEA', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('MEXICO', 'MXN')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddCLABE(null)
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddPostCode('11115')
        recipientlist.AddState('washington')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('MEXICO')
        recipientlist.clickAddRecipient()
        recipientlist.validateCLABEError()
    })
    it('TC_AC-11-  Verify that if Currency= TRY and Country = UNITED KINGDOM & client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'TRY')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-12-  Verify that if Currency= TRY and Country = TURKEY & client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('TUR', 'TRY')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-13-  Verify that if Currency= TRY and Country = UNITED KINGDOM & client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'TRY')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-14-  Verify that if Currency= TRY and Country = TURKEY & client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('TUR', 'TRY')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-15-  Verify that if Currency= KWD and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'KWD')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-16-   Verify that if Currency= KWD and Country = Kuwait & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('KU', 'KWD')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('KUWAIT')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-17-  Verify that if Currency= OMR and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'OMR')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-18-Verify that if Currency= OMR and Country = OMAN & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('OMAN', 'OMR')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddAccountNumber('13071472')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('OMAN')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-19 Verify that if Currency= SAR and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'SAR')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-20 Verify that if Currency= SAR and Country = SAUDI ARABIA & Client = UK and check priority settlement is enabled ', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('SAUDI', 'SAR')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('SAUDI ARABIA')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })

    it('TC_AC-21 Verify that if Currency= SAR and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'SAR')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-22 Verify that if Currency= SAR and Country = SAUDI ARABIA & Client = EEA and check priority settlement is enabled ', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('SAUDI', 'SAR')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('SAUDI ARABIA')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-23  Verify that if Currency= QAR and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled ', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'QAR')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-24  Verify that if Currency= QAR and Country = QATAR & Client = UK and check priority settlement is enabled ', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('QA', 'QAR')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('QATAR')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-25  Verify that if Currency= CZK and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled ', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'CZK')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-26 Verify that if Currency= CZK and Country = Czech Republic & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('CZ', 'CZK')
        recipientlist.AddIBAN('CZ6508000000192000145399')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('CZECH REPUBLIC')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-27  Verify that if Currency= CZK and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'CZK')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-28 Verify that if Currency= CZK and Country = Czech Republic & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('CZ', 'CZK')
        recipientlist.AddIBAN('CZ6508000000192000145399')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('CZECH REPUBLIC')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-29 Verify that if Currency= RON and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'RON')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-30   Verify that if Currency= RON and Country = ROMANIA & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('ROMANIA', 'RON')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('ROMANIA')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-31  Verify that if Currency= RON and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'RON')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-32 Verify that if Currency= RON and Country = ROMANIA & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('ROMANIA', 'RON')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('ROMANIA')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-33   Verify that if Currency= ILS and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'ILS')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-34  Verify that if Currency= ILS and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('ISR', 'ILS')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('ISRAEL')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-35  Verify that if Currency= HUF and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'HUF')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-36 Verify that if Currency= HUF and Country = HUNGARY & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('HUN', 'HUF')
        recipientlist.AddIBAN('HU42117730161111101800000000')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('HUNGARY')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-37 Verify that if Currency= HUF and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'HUF')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-38 Verify that if Currency= HUF and Country = HUNGARY & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('HUN', 'HUF')
        recipientlist.AddIBAN('HU42117730161111101800000000')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('HUNGARY')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-39   Verify that if Currency= KES and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'KES')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-40 Verify that if Currency= KES and Country = KENYA & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('KEN', 'KES')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddAccountNumber('13071472')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('KENYA')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-41 Verify that if Currency= KES and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'KES')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-42 Verify that if Currency= KES and Country = KENYA & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('KEN', 'KES')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddAccountNumber('13071472')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('KENYA')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-43  Verify that if Currency= UGX and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'UGX')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-44  Verify that if Currency= UGX and Country = UGANDA & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UGAN', 'UGX')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddAccountNumber('13071472')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UGANDA')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-45  Verify that if Currency= BHD and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'BHD')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.SelectPaymentPurpose('Payment of Invoice(s)')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-46   Verify that if Currency= BHD and Country = BAHRAIN & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('BAHR', 'BHD')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('BAHRAIN')
        recipientlist.SelectPaymentPurpose('Computer services')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()

    })
    it('TC_AC-47 if Country =BAHRAIN regardless of currency & Client = UK and check add recipient journey requies a payment purpose code', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('BAHR', 'BHD')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('BAHRAIN')
        recipientlist.SelectPaymentPurpose(null)
        recipientlist.clickAddRecipient()
        recipientlist.ValidatePaymentPurposeError('Please select Payment Purpose')
    })
    it('TC_AC-48 Verify that if Currency= AED and Country = UNITED KINGDOM & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'AED')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.SelectPaymentPurpose('Payment of Invoice(s)')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-49 Verify that if Currency= AED and Country = United Arab Emirates & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UNITED A', 'AED')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED ARAB EMIRATES')
        recipientlist.SelectPaymentPurpose('Agency Commission')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })

    it('TC_AC-50 Verify that if Currency= AED and Country = UNITED KINGDOM & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UN', 'AED')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED KINGDOM')
        recipientlist.SelectPaymentPurpose('Payment of Invoice(s)')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-51 Verify that if Currency= AED and Country = United Arab Emirates & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UNITED A', 'AED')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('UNITED ARAB EMIRATES')
        recipientlist.SelectPaymentPurpose('Agency Commission')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it('TC_AC-52   Verify that if Country = United Arab Emirates regardless of currency & Client = UK and check add recipient journey requies a payment purpose code', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('UNITED A', 'BHD')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddSwiftcodeBIC('BARCGB22')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('BAHRAIN')
        recipientlist.SelectPaymentPurpose(null)
        recipientlist.clickAddRecipient()
        recipientlist.ValidatePaymentPurposeError('Please select Payment Purpose')
    })
    it.only('TC_AC-53  Verify that if Currency= INR and Country = INDIA & Client = UK and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userName, password)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('IN', 'INR')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddIFSC('PUNB0006700')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('INDIA')
        recipientlist.SelectPaymentPurpose('Education-related student expenses')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })
    it.only('TC_AC-54 if Currency= INR and Country = INDIA & Client = EEA and check priority settlement is enabled', () => {
        cy.visit('/login')
        signinpage.Signin(userEEA, passwordEEA)
        signinpage.clickLogin()
        cy.url().should('include', '/wallet/dashboard')
        recipientlist.gotoRecipientList()
        recipientlist.gotoAddRecipient()
        recipientlist.ValidateAddRecipient('IN', 'INR')
        recipientlist.AddIBAN('GB06BARC20060513071472')
        recipientlist.AddIFSC('PUNB0006700')
        recipientlist.AddRecipientType()
        recipientlist.AddBusinessname('Test2')
        recipientlist.AddBusinessDescription('New business')
        recipientlist.AddBusinessNature('finance')
        recipientlist.AddAddress('H240')
        recipientlist.AddCity('Manchester')
        recipientlist.SelectRecipientCountry('INDIA')
        recipientlist.SelectPaymentPurpose('Education-related student expenses')
        recipientlist.clickAddRecipient()
        recipientlist.gotoPayRecipient()
        newpayment.EnabledPriorityButton()
        newpayment.DisabledRegularButton()
    })





  

  

   









})